[package]
name = "rust-ml"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

piston = "0.53"
piston2d-graphics = "0.43"
pistoncore-glutin_window = "0.71"
piston2d-opengl_graphics = "0.82"